### ISSUE TITLE
Add https://github.com/AlexC-ux/Arina-OSINT

### ISSUE THREAD

**Issue by soxoj** [soxoj/osint-namecheckers-list#6]

**Comment by soxoj** [comment]
Added in 9c31ead1f90a0ae3fef9c85dbc5266cceeba2ecd

**Comment by AlexC-ux** [comment]
**Thank** you for your **support**!
**Publishing** my project in your repository shows that **my work is not in vain**.

`printf("Thanks, %s", username);`

**Comment by soxoj** [comment]
Thank you for your job! 👍
